---

  - name: Generate self-signed SSL certificate
    command: >
      openssl req
        -batch
        -new
        -x509
        -nodes
        -extensions v3_ca
        -sha256
        -newkey "rsa:{{ ssl_certs_key_size }}"
        -days "{{ ssl_certs_days }}"
        -subj "{{ ssl_certs_fields }}"
        -keyout "{{ ssl_certs_privkey_path }}"
        -out "{{ ssl_certs_cert_path }}"
    args:
      creates: "{{ ssl_certs_cert_path }}"
    when: ssl_certs_generate_self_signed

  - name: RSA key file ownership
    file:
      path: "{{ ssl_certs_privkey_path }}"
      owner: "{{ ssl_certs_path_owner }}"
      group: "{{ ssl_certs_path_group }}"
      mode: "{{ ssl_certs_mode }}"
    when: ssl_certs_generate_self_signed

  - name: Self-signed SSL certificate file ownership
    file:
      path: "{{ ssl_certs_cert_path }}"
      owner: "{{ ssl_certs_path_owner }}"
      group: "{{ ssl_certs_path_group }}"
      mode: "{{ ssl_certs_mode }}"
    when: ssl_certs_generate_self_signed
